//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Seguimiento_y_Control.Entity.Traspasos
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class Traspasos_Entities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto Traspasos_Entities usando la cadena de conexión encontrada en la sección 'Traspasos_Entities' del archivo de configuración de la aplicación.
        /// </summary>
        public Traspasos_Entities() : base("name=Traspasos_Entities", "Traspasos_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto Traspasos_Entities.
        /// </summary>
        public Traspasos_Entities(string connectionString) : base(connectionString, "Traspasos_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto Traspasos_Entities.
        /// </summary>
        public Traspasos_Entities(EntityConnection connection) : base(connection, "Traspasos_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<empresas> empresas
        {
            get
            {
                if ((_empresas == null))
                {
                    _empresas = base.CreateObjectSet<empresas>("empresas");
                }
                return _empresas;
            }
        }
        private ObjectSet<empresas> _empresas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<etiquetas> etiquetas
        {
            get
            {
                if ((_etiquetas == null))
                {
                    _etiquetas = base.CreateObjectSet<etiquetas>("etiquetas");
                }
                return _etiquetas;
            }
        }
        private ObjectSet<etiquetas> _etiquetas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<paquetes> paquetes
        {
            get
            {
                if ((_paquetes == null))
                {
                    _paquetes = base.CreateObjectSet<paquetes>("paquetes");
                }
                return _paquetes;
            }
        }
        private ObjectSet<paquetes> _paquetes;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet empresas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToempresas(empresas empresas)
        {
            base.AddObject("empresas", empresas);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet etiquetas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToetiquetas(etiquetas etiquetas)
        {
            base.AddObject("etiquetas", etiquetas);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet paquetes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTopaquetes(paquetes paquetes)
        {
            base.AddObject("paquetes", paquetes);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Traspasos_Model", Name="empresas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class empresas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto empresas.
        /// </summary>
        /// <param name="id_empresa">Valor inicial de la propiedad id_empresa.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        public static empresas Createempresas(global::System.Int64 id_empresa, global::System.String nombre)
        {
            empresas empresas = new empresas();
            empresas.id_empresa = id_empresa;
            empresas.nombre = nombre;
            return empresas;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_empresa
        {
            get
            {
                return _id_empresa;
            }
            set
            {
                if (_id_empresa != value)
                {
                    Onid_empresaChanging(value);
                    ReportPropertyChanging("id_empresa");
                    _id_empresa = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_empresa");
                    Onid_empresaChanged();
                }
            }
        }
        private global::System.Int64 _id_empresa;
        partial void Onid_empresaChanging(global::System.Int64 value);
        partial void Onid_empresaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Traspasos_Model", Name="etiquetas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class etiquetas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto etiquetas.
        /// </summary>
        /// <param name="id_etiqueta">Valor inicial de la propiedad id_etiqueta.</param>
        /// <param name="numero_etiqueta">Valor inicial de la propiedad numero_etiqueta.</param>
        /// <param name="tipo_etiqueta">Valor inicial de la propiedad tipo_etiqueta.</param>
        /// <param name="id_lote_origen">Valor inicial de la propiedad id_lote_origen.</param>
        /// <param name="clave_articulo">Valor inicial de la propiedad clave_articulo.</param>
        /// <param name="fecha_empaque">Valor inicial de la propiedad fecha_empaque.</param>
        /// <param name="fecha_caducidad">Valor inicial de la propiedad fecha_caducidad.</param>
        /// <param name="cantidad">Valor inicial de la propiedad cantidad.</param>
        /// <param name="unidad">Valor inicial de la propiedad unidad.</param>
        /// <param name="id_empresa_destino">Valor inicial de la propiedad id_empresa_destino.</param>
        /// <param name="id_empresa_origen">Valor inicial de la propiedad id_empresa_origen.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        public static etiquetas Createetiquetas(global::System.Int64 id_etiqueta, global::System.String numero_etiqueta, global::System.String tipo_etiqueta, global::System.Int64 id_lote_origen, global::System.String clave_articulo, global::System.DateTime fecha_empaque, global::System.DateTime fecha_caducidad, global::System.Decimal cantidad, global::System.String unidad, global::System.Int64 id_empresa_destino, global::System.Int64 id_empresa_origen, global::System.String estado)
        {
            etiquetas etiquetas = new etiquetas();
            etiquetas.id_etiqueta = id_etiqueta;
            etiquetas.numero_etiqueta = numero_etiqueta;
            etiquetas.tipo_etiqueta = tipo_etiqueta;
            etiquetas.id_lote_origen = id_lote_origen;
            etiquetas.clave_articulo = clave_articulo;
            etiquetas.fecha_empaque = fecha_empaque;
            etiquetas.fecha_caducidad = fecha_caducidad;
            etiquetas.cantidad = cantidad;
            etiquetas.unidad = unidad;
            etiquetas.id_empresa_destino = id_empresa_destino;
            etiquetas.id_empresa_origen = id_empresa_origen;
            etiquetas.estado = estado;
            return etiquetas;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_etiqueta
        {
            get
            {
                return _id_etiqueta;
            }
            set
            {
                if (_id_etiqueta != value)
                {
                    Onid_etiquetaChanging(value);
                    ReportPropertyChanging("id_etiqueta");
                    _id_etiqueta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_etiqueta");
                    Onid_etiquetaChanged();
                }
            }
        }
        private global::System.Int64 _id_etiqueta;
        partial void Onid_etiquetaChanging(global::System.Int64 value);
        partial void Onid_etiquetaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String numero_etiqueta
        {
            get
            {
                return _numero_etiqueta;
            }
            set
            {
                Onnumero_etiquetaChanging(value);
                ReportPropertyChanging("numero_etiqueta");
                _numero_etiqueta = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("numero_etiqueta");
                Onnumero_etiquetaChanged();
            }
        }
        private global::System.String _numero_etiqueta;
        partial void Onnumero_etiquetaChanging(global::System.String value);
        partial void Onnumero_etiquetaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tipo_etiqueta
        {
            get
            {
                return _tipo_etiqueta;
            }
            set
            {
                Ontipo_etiquetaChanging(value);
                ReportPropertyChanging("tipo_etiqueta");
                _tipo_etiqueta = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tipo_etiqueta");
                Ontipo_etiquetaChanged();
            }
        }
        private global::System.String _tipo_etiqueta;
        partial void Ontipo_etiquetaChanging(global::System.String value);
        partial void Ontipo_etiquetaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_lote_origen
        {
            get
            {
                return _id_lote_origen;
            }
            set
            {
                Onid_lote_origenChanging(value);
                ReportPropertyChanging("id_lote_origen");
                _id_lote_origen = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_lote_origen");
                Onid_lote_origenChanged();
            }
        }
        private global::System.Int64 _id_lote_origen;
        partial void Onid_lote_origenChanging(global::System.Int64 value);
        partial void Onid_lote_origenChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String clave_articulo
        {
            get
            {
                return _clave_articulo;
            }
            set
            {
                Onclave_articuloChanging(value);
                ReportPropertyChanging("clave_articulo");
                _clave_articulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("clave_articulo");
                Onclave_articuloChanged();
            }
        }
        private global::System.String _clave_articulo;
        partial void Onclave_articuloChanging(global::System.String value);
        partial void Onclave_articuloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_empaque
        {
            get
            {
                return _fecha_empaque;
            }
            set
            {
                Onfecha_empaqueChanging(value);
                ReportPropertyChanging("fecha_empaque");
                _fecha_empaque = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_empaque");
                Onfecha_empaqueChanged();
            }
        }
        private global::System.DateTime _fecha_empaque;
        partial void Onfecha_empaqueChanging(global::System.DateTime value);
        partial void Onfecha_empaqueChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_caducidad
        {
            get
            {
                return _fecha_caducidad;
            }
            set
            {
                Onfecha_caducidadChanging(value);
                ReportPropertyChanging("fecha_caducidad");
                _fecha_caducidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_caducidad");
                Onfecha_caducidadChanged();
            }
        }
        private global::System.DateTime _fecha_caducidad;
        partial void Onfecha_caducidadChanging(global::System.DateTime value);
        partial void Onfecha_caducidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal cantidad
        {
            get
            {
                return _cantidad;
            }
            set
            {
                OncantidadChanging(value);
                ReportPropertyChanging("cantidad");
                _cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cantidad");
                OncantidadChanged();
            }
        }
        private global::System.Decimal _cantidad;
        partial void OncantidadChanging(global::System.Decimal value);
        partial void OncantidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String unidad
        {
            get
            {
                return _unidad;
            }
            set
            {
                OnunidadChanging(value);
                ReportPropertyChanging("unidad");
                _unidad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("unidad");
                OnunidadChanged();
            }
        }
        private global::System.String _unidad;
        partial void OnunidadChanging(global::System.String value);
        partial void OnunidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> piezas
        {
            get
            {
                return _piezas;
            }
            set
            {
                OnpiezasChanging(value);
                ReportPropertyChanging("piezas");
                _piezas = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("piezas");
                OnpiezasChanged();
            }
        }
        private Nullable<global::System.Int64> _piezas;
        partial void OnpiezasChanging(Nullable<global::System.Int64> value);
        partial void OnpiezasChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_empresa_destino
        {
            get
            {
                return _id_empresa_destino;
            }
            set
            {
                Onid_empresa_destinoChanging(value);
                ReportPropertyChanging("id_empresa_destino");
                _id_empresa_destino = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_empresa_destino");
                Onid_empresa_destinoChanged();
            }
        }
        private global::System.Int64 _id_empresa_destino;
        partial void Onid_empresa_destinoChanging(global::System.Int64 value);
        partial void Onid_empresa_destinoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_empresa_origen
        {
            get
            {
                return _id_empresa_origen;
            }
            set
            {
                Onid_empresa_origenChanging(value);
                ReportPropertyChanging("id_empresa_origen");
                _id_empresa_origen = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_empresa_origen");
                Onid_empresa_origenChanged();
            }
        }
        private global::System.Int64 _id_empresa_origen;
        partial void Onid_empresa_origenChanging(global::System.Int64 value);
        partial void Onid_empresa_origenChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.String _estado;
        partial void OnestadoChanging(global::System.String value);
        partial void OnestadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numero_etiqueta_contenedor
        {
            get
            {
                return _numero_etiqueta_contenedor;
            }
            set
            {
                Onnumero_etiqueta_contenedorChanging(value);
                ReportPropertyChanging("numero_etiqueta_contenedor");
                _numero_etiqueta_contenedor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numero_etiqueta_contenedor");
                Onnumero_etiqueta_contenedorChanged();
            }
        }
        private global::System.String _numero_etiqueta_contenedor;
        partial void Onnumero_etiqueta_contenedorChanging(global::System.String value);
        partial void Onnumero_etiqueta_contenedorChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Traspasos_Model", Name="paquetes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class paquetes : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto paquetes.
        /// </summary>
        /// <param name="id_paquetes">Valor inicial de la propiedad id_paquetes.</param>
        /// <param name="numero_etiqueta">Valor inicial de la propiedad numero_etiqueta.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        /// <param name="cantidad">Valor inicial de la propiedad cantidad.</param>
        /// <param name="unidad">Valor inicial de la propiedad unidad.</param>
        /// <param name="id_pedido_origen">Valor inicial de la propiedad id_pedido_origen.</param>
        /// <param name="fecha_creacion">Valor inicial de la propiedad fecha_creacion.</param>
        /// <param name="fecha_caducidad">Valor inicial de la propiedad fecha_caducidad.</param>
        /// <param name="id_empresa_origen">Valor inicial de la propiedad id_empresa_origen.</param>
        /// <param name="id_empresa_destino">Valor inicial de la propiedad id_empresa_destino.</param>
        public static paquetes Createpaquetes(global::System.Int64 id_paquetes, global::System.String numero_etiqueta, global::System.String estado, global::System.Decimal cantidad, global::System.String unidad, global::System.Int64 id_pedido_origen, global::System.DateTime fecha_creacion, global::System.DateTime fecha_caducidad, global::System.Int64 id_empresa_origen, global::System.Int64 id_empresa_destino)
        {
            paquetes paquetes = new paquetes();
            paquetes.id_paquetes = id_paquetes;
            paquetes.numero_etiqueta = numero_etiqueta;
            paquetes.estado = estado;
            paquetes.cantidad = cantidad;
            paquetes.unidad = unidad;
            paquetes.id_pedido_origen = id_pedido_origen;
            paquetes.fecha_creacion = fecha_creacion;
            paquetes.fecha_caducidad = fecha_caducidad;
            paquetes.id_empresa_origen = id_empresa_origen;
            paquetes.id_empresa_destino = id_empresa_destino;
            return paquetes;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_paquetes
        {
            get
            {
                return _id_paquetes;
            }
            set
            {
                if (_id_paquetes != value)
                {
                    Onid_paquetesChanging(value);
                    ReportPropertyChanging("id_paquetes");
                    _id_paquetes = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_paquetes");
                    Onid_paquetesChanged();
                }
            }
        }
        private global::System.Int64 _id_paquetes;
        partial void Onid_paquetesChanging(global::System.Int64 value);
        partial void Onid_paquetesChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String numero_etiqueta
        {
            get
            {
                return _numero_etiqueta;
            }
            set
            {
                Onnumero_etiquetaChanging(value);
                ReportPropertyChanging("numero_etiqueta");
                _numero_etiqueta = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("numero_etiqueta");
                Onnumero_etiquetaChanged();
            }
        }
        private global::System.String _numero_etiqueta;
        partial void Onnumero_etiquetaChanging(global::System.String value);
        partial void Onnumero_etiquetaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.String _estado;
        partial void OnestadoChanging(global::System.String value);
        partial void OnestadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal cantidad
        {
            get
            {
                return _cantidad;
            }
            set
            {
                OncantidadChanging(value);
                ReportPropertyChanging("cantidad");
                _cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cantidad");
                OncantidadChanged();
            }
        }
        private global::System.Decimal _cantidad;
        partial void OncantidadChanging(global::System.Decimal value);
        partial void OncantidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String unidad
        {
            get
            {
                return _unidad;
            }
            set
            {
                OnunidadChanging(value);
                ReportPropertyChanging("unidad");
                _unidad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("unidad");
                OnunidadChanged();
            }
        }
        private global::System.String _unidad;
        partial void OnunidadChanging(global::System.String value);
        partial void OnunidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_pedido_origen
        {
            get
            {
                return _id_pedido_origen;
            }
            set
            {
                Onid_pedido_origenChanging(value);
                ReportPropertyChanging("id_pedido_origen");
                _id_pedido_origen = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_pedido_origen");
                Onid_pedido_origenChanged();
            }
        }
        private global::System.Int64 _id_pedido_origen;
        partial void Onid_pedido_origenChanging(global::System.Int64 value);
        partial void Onid_pedido_origenChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_creacion
        {
            get
            {
                return _fecha_creacion;
            }
            set
            {
                Onfecha_creacionChanging(value);
                ReportPropertyChanging("fecha_creacion");
                _fecha_creacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_creacion");
                Onfecha_creacionChanged();
            }
        }
        private global::System.DateTime _fecha_creacion;
        partial void Onfecha_creacionChanging(global::System.DateTime value);
        partial void Onfecha_creacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_caducidad
        {
            get
            {
                return _fecha_caducidad;
            }
            set
            {
                Onfecha_caducidadChanging(value);
                ReportPropertyChanging("fecha_caducidad");
                _fecha_caducidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_caducidad");
                Onfecha_caducidadChanged();
            }
        }
        private global::System.DateTime _fecha_caducidad;
        partial void Onfecha_caducidadChanging(global::System.DateTime value);
        partial void Onfecha_caducidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_empresa_origen
        {
            get
            {
                return _id_empresa_origen;
            }
            set
            {
                Onid_empresa_origenChanging(value);
                ReportPropertyChanging("id_empresa_origen");
                _id_empresa_origen = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_empresa_origen");
                Onid_empresa_origenChanged();
            }
        }
        private global::System.Int64 _id_empresa_origen;
        partial void Onid_empresa_origenChanging(global::System.Int64 value);
        partial void Onid_empresa_origenChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_empresa_destino
        {
            get
            {
                return _id_empresa_destino;
            }
            set
            {
                Onid_empresa_destinoChanging(value);
                ReportPropertyChanging("id_empresa_destino");
                _id_empresa_destino = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_empresa_destino");
                Onid_empresa_destinoChanged();
            }
        }
        private global::System.Int64 _id_empresa_destino;
        partial void Onid_empresa_destinoChanging(global::System.Int64 value);
        partial void Onid_empresa_destinoChanged();

        #endregion
    
    }

    #endregion
    
}
