//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Seguimiento_y_Control.Entity
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class Seguimiento_ACC_Entities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto Seguimiento_ACC_Entities usando la cadena de conexión encontrada en la sección 'Seguimiento_ACC_Entities' del archivo de configuración de la aplicación.
        /// </summary>
        public Seguimiento_ACC_Entities() : base("name=Seguimiento_ACC_Entities", "Seguimiento_ACC_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto Seguimiento_ACC_Entities.
        /// </summary>
        public Seguimiento_ACC_Entities(string connectionString) : base(connectionString, "Seguimiento_ACC_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto Seguimiento_ACC_Entities.
        /// </summary>
        public Seguimiento_ACC_Entities(EntityConnection connection) : base(connection, "Seguimiento_ACC_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<areas> areas
        {
            get
            {
                if ((_areas == null))
                {
                    _areas = base.CreateObjectSet<areas>("areas");
                }
                return _areas;
            }
        }
        private ObjectSet<areas> _areas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<articulos> articulos
        {
            get
            {
                if ((_articulos == null))
                {
                    _articulos = base.CreateObjectSet<articulos>("articulos");
                }
                return _articulos;
            }
        }
        private ObjectSet<articulos> _articulos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<articulos_unidades> articulos_unidades
        {
            get
            {
                if ((_articulos_unidades == null))
                {
                    _articulos_unidades = base.CreateObjectSet<articulos_unidades>("articulos_unidades");
                }
                return _articulos_unidades;
            }
        }
        private ObjectSet<articulos_unidades> _articulos_unidades;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<bodegas> bodegas
        {
            get
            {
                if ((_bodegas == null))
                {
                    _bodegas = base.CreateObjectSet<bodegas>("bodegas");
                }
                return _bodegas;
            }
        }
        private ObjectSet<bodegas> _bodegas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<pesos_fijos> pesos_fijos
        {
            get
            {
                if ((_pesos_fijos == null))
                {
                    _pesos_fijos = base.CreateObjectSet<pesos_fijos>("pesos_fijos");
                }
                return _pesos_fijos;
            }
        }
        private ObjectSet<pesos_fijos> _pesos_fijos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<proveedores> proveedores
        {
            get
            {
                if ((_proveedores == null))
                {
                    _proveedores = base.CreateObjectSet<proveedores>("proveedores");
                }
                return _proveedores;
            }
        }
        private ObjectSet<proveedores> _proveedores;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<unidades> unidades
        {
            get
            {
                if ((_unidades == null))
                {
                    _unidades = base.CreateObjectSet<unidades>("unidades");
                }
                return _unidades;
            }
        }
        private ObjectSet<unidades> _unidades;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<usuarios> usuarios
        {
            get
            {
                if ((_usuarios == null))
                {
                    _usuarios = base.CreateObjectSet<usuarios>("usuarios");
                }
                return _usuarios;
            }
        }
        private ObjectSet<usuarios> _usuarios;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<etiquetas> etiquetas
        {
            get
            {
                if ((_etiquetas == null))
                {
                    _etiquetas = base.CreateObjectSet<etiquetas>("etiquetas");
                }
                return _etiquetas;
            }
        }
        private ObjectSet<etiquetas> _etiquetas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<lotes> lotes
        {
            get
            {
                if ((_lotes == null))
                {
                    _lotes = base.CreateObjectSet<lotes>("lotes");
                }
                return _lotes;
            }
        }
        private ObjectSet<lotes> _lotes;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet areas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToareas(areas areas)
        {
            base.AddObject("areas", areas);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet articulos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToarticulos(articulos articulos)
        {
            base.AddObject("articulos", articulos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet articulos_unidades. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToarticulos_unidades(articulos_unidades articulos_unidades)
        {
            base.AddObject("articulos_unidades", articulos_unidades);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet bodegas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTobodegas(bodegas bodegas)
        {
            base.AddObject("bodegas", bodegas);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet pesos_fijos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTopesos_fijos(pesos_fijos pesos_fijos)
        {
            base.AddObject("pesos_fijos", pesos_fijos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet proveedores. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToproveedores(proveedores proveedores)
        {
            base.AddObject("proveedores", proveedores);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet unidades. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTounidades(unidades unidades)
        {
            base.AddObject("unidades", unidades);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet usuarios. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTousuarios(usuarios usuarios)
        {
            base.AddObject("usuarios", usuarios);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet etiquetas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToetiquetas(etiquetas etiquetas)
        {
            base.AddObject("etiquetas", etiquetas);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet lotes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTolotes(lotes lotes)
        {
            base.AddObject("lotes", lotes);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SeguimientoContext", Name="areas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class areas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto areas.
        /// </summary>
        /// <param name="id_area">Valor inicial de la propiedad id_area.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        public static areas Createareas(global::System.Int32 id_area, global::System.String nombre)
        {
            areas areas = new areas();
            areas.id_area = id_area;
            areas.nombre = nombre;
            return areas;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_area
        {
            get
            {
                return _id_area;
            }
            set
            {
                if (_id_area != value)
                {
                    Onid_areaChanging(value);
                    ReportPropertyChanging("id_area");
                    _id_area = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_area");
                    Onid_areaChanged();
                }
            }
        }
        private global::System.Int32 _id_area;
        partial void Onid_areaChanging(global::System.Int32 value);
        partial void Onid_areaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SeguimientoContext", Name="articulos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class articulos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto articulos.
        /// </summary>
        /// <param name="clave">Valor inicial de la propiedad clave.</param>
        /// <param name="articulo">Valor inicial de la propiedad articulo.</param>
        /// <param name="dias_caducidad">Valor inicial de la propiedad dias_caducidad.</param>
        /// <param name="id_bodega">Valor inicial de la propiedad id_bodega.</param>
        /// <param name="peso_variado">Valor inicial de la propiedad peso_variado.</param>
        /// <param name="parcial">Valor inicial de la propiedad parcial.</param>
        /// <param name="leyenda">Valor inicial de la propiedad leyenda.</param>
        public static articulos Createarticulos(global::System.String clave, global::System.String articulo, global::System.Int32 dias_caducidad, global::System.Int32 id_bodega, global::System.Boolean peso_variado, global::System.Boolean parcial, global::System.Boolean leyenda)
        {
            articulos articulos = new articulos();
            articulos.clave = clave;
            articulos.articulo = articulo;
            articulos.dias_caducidad = dias_caducidad;
            articulos.id_bodega = id_bodega;
            articulos.peso_variado = peso_variado;
            articulos.parcial = parcial;
            articulos.leyenda = leyenda;
            return articulos;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String clave
        {
            get
            {
                return _clave;
            }
            set
            {
                if (_clave != value)
                {
                    OnclaveChanging(value);
                    ReportPropertyChanging("clave");
                    _clave = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("clave");
                    OnclaveChanged();
                }
            }
        }
        private global::System.String _clave;
        partial void OnclaveChanging(global::System.String value);
        partial void OnclaveChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String articulo
        {
            get
            {
                return _articulo;
            }
            set
            {
                OnarticuloChanging(value);
                ReportPropertyChanging("articulo");
                _articulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("articulo");
                OnarticuloChanged();
            }
        }
        private global::System.String _articulo;
        partial void OnarticuloChanging(global::System.String value);
        partial void OnarticuloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 dias_caducidad
        {
            get
            {
                return _dias_caducidad;
            }
            set
            {
                Ondias_caducidadChanging(value);
                ReportPropertyChanging("dias_caducidad");
                _dias_caducidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dias_caducidad");
                Ondias_caducidadChanged();
            }
        }
        private global::System.Int32 _dias_caducidad;
        partial void Ondias_caducidadChanging(global::System.Int32 value);
        partial void Ondias_caducidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_bodega
        {
            get
            {
                return _id_bodega;
            }
            set
            {
                Onid_bodegaChanging(value);
                ReportPropertyChanging("id_bodega");
                _id_bodega = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_bodega");
                Onid_bodegaChanged();
            }
        }
        private global::System.Int32 _id_bodega;
        partial void Onid_bodegaChanging(global::System.Int32 value);
        partial void Onid_bodegaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean peso_variado
        {
            get
            {
                return _peso_variado;
            }
            set
            {
                Onpeso_variadoChanging(value);
                ReportPropertyChanging("peso_variado");
                _peso_variado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("peso_variado");
                Onpeso_variadoChanged();
            }
        }
        private global::System.Boolean _peso_variado;
        partial void Onpeso_variadoChanging(global::System.Boolean value);
        partial void Onpeso_variadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean parcial
        {
            get
            {
                return _parcial;
            }
            set
            {
                OnparcialChanging(value);
                ReportPropertyChanging("parcial");
                _parcial = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("parcial");
                OnparcialChanged();
            }
        }
        private global::System.Boolean _parcial;
        partial void OnparcialChanging(global::System.Boolean value);
        partial void OnparcialChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean leyenda
        {
            get
            {
                return _leyenda;
            }
            set
            {
                OnleyendaChanging(value);
                ReportPropertyChanging("leyenda");
                _leyenda = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("leyenda");
                OnleyendaChanged();
            }
        }
        private global::System.Boolean _leyenda;
        partial void OnleyendaChanging(global::System.Boolean value);
        partial void OnleyendaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> cantidad_fija
        {
            get
            {
                return _cantidad_fija;
            }
            set
            {
                Oncantidad_fijaChanging(value);
                ReportPropertyChanging("cantidad_fija");
                _cantidad_fija = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cantidad_fija");
                Oncantidad_fijaChanged();
            }
        }
        private Nullable<global::System.Int32> _cantidad_fija;
        partial void Oncantidad_fijaChanging(Nullable<global::System.Int32> value);
        partial void Oncantidad_fijaChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SeguimientoContext", Name="articulos_unidades")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class articulos_unidades : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto articulos_unidades.
        /// </summary>
        /// <param name="id_articulo">Valor inicial de la propiedad id_articulo.</param>
        /// <param name="id_unidad">Valor inicial de la propiedad id_unidad.</param>
        public static articulos_unidades Createarticulos_unidades(global::System.Int32 id_articulo, global::System.Int32 id_unidad)
        {
            articulos_unidades articulos_unidades = new articulos_unidades();
            articulos_unidades.id_articulo = id_articulo;
            articulos_unidades.id_unidad = id_unidad;
            return articulos_unidades;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_articulo
        {
            get
            {
                return _id_articulo;
            }
            set
            {
                if (_id_articulo != value)
                {
                    Onid_articuloChanging(value);
                    ReportPropertyChanging("id_articulo");
                    _id_articulo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_articulo");
                    Onid_articuloChanged();
                }
            }
        }
        private global::System.Int32 _id_articulo;
        partial void Onid_articuloChanging(global::System.Int32 value);
        partial void Onid_articuloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_unidad
        {
            get
            {
                return _id_unidad;
            }
            set
            {
                if (_id_unidad != value)
                {
                    Onid_unidadChanging(value);
                    ReportPropertyChanging("id_unidad");
                    _id_unidad = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_unidad");
                    Onid_unidadChanged();
                }
            }
        }
        private global::System.Int32 _id_unidad;
        partial void Onid_unidadChanging(global::System.Int32 value);
        partial void Onid_unidadChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SeguimientoContext", Name="bodegas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class bodegas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto bodegas.
        /// </summary>
        /// <param name="id_bodega">Valor inicial de la propiedad id_bodega.</param>
        /// <param name="bodega">Valor inicial de la propiedad bodega.</param>
        public static bodegas Createbodegas(global::System.Int32 id_bodega, global::System.String bodega)
        {
            bodegas bodegas = new bodegas();
            bodegas.id_bodega = id_bodega;
            bodegas.bodega = bodega;
            return bodegas;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_bodega
        {
            get
            {
                return _id_bodega;
            }
            set
            {
                if (_id_bodega != value)
                {
                    Onid_bodegaChanging(value);
                    ReportPropertyChanging("id_bodega");
                    _id_bodega = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_bodega");
                    Onid_bodegaChanged();
                }
            }
        }
        private global::System.Int32 _id_bodega;
        partial void Onid_bodegaChanging(global::System.Int32 value);
        partial void Onid_bodegaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String bodega
        {
            get
            {
                return _bodega;
            }
            set
            {
                OnbodegaChanging(value);
                ReportPropertyChanging("bodega");
                _bodega = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("bodega");
                OnbodegaChanged();
            }
        }
        private global::System.String _bodega;
        partial void OnbodegaChanging(global::System.String value);
        partial void OnbodegaChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SeguimientoContext", Name="etiquetas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class etiquetas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto etiquetas.
        /// </summary>
        /// <param name="id_etiqueta">Valor inicial de la propiedad id_etiqueta.</param>
        /// <param name="numero_etiqueta">Valor inicial de la propiedad numero_etiqueta.</param>
        /// <param name="tipo_etiqueta">Valor inicial de la propiedad tipo_etiqueta.</param>
        /// <param name="etiquetascol">Valor inicial de la propiedad etiquetascol.</param>
        /// <param name="id_lote">Valor inicial de la propiedad id_lote.</param>
        /// <param name="clave_articulo">Valor inicial de la propiedad clave_articulo.</param>
        /// <param name="fecha_empaque">Valor inicial de la propiedad fecha_empaque.</param>
        /// <param name="fecha_caducidad">Valor inicial de la propiedad fecha_caducidad.</param>
        /// <param name="id_bodega">Valor inicial de la propiedad id_bodega.</param>
        /// <param name="id_usuario">Valor inicial de la propiedad id_usuario.</param>
        /// <param name="cantidad">Valor inicial de la propiedad cantidad.</param>
        /// <param name="unidad">Valor inicial de la propiedad unidad.</param>
        public static etiquetas Createetiquetas(global::System.Int32 id_etiqueta, global::System.String numero_etiqueta, global::System.String tipo_etiqueta, global::System.String etiquetascol, global::System.Int32 id_lote, global::System.String clave_articulo, global::System.DateTime fecha_empaque, global::System.DateTime fecha_caducidad, global::System.Int32 id_bodega, global::System.Int32 id_usuario, global::System.Single cantidad, global::System.String unidad)
        {
            etiquetas etiquetas = new etiquetas();
            etiquetas.id_etiqueta = id_etiqueta;
            etiquetas.numero_etiqueta = numero_etiqueta;
            etiquetas.tipo_etiqueta = tipo_etiqueta;
            etiquetas.etiquetascol = etiquetascol;
            etiquetas.id_lote = id_lote;
            etiquetas.clave_articulo = clave_articulo;
            etiquetas.fecha_empaque = fecha_empaque;
            etiquetas.fecha_caducidad = fecha_caducidad;
            etiquetas.id_bodega = id_bodega;
            etiquetas.id_usuario = id_usuario;
            etiquetas.cantidad = cantidad;
            etiquetas.unidad = unidad;
            return etiquetas;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_etiqueta
        {
            get
            {
                return _id_etiqueta;
            }
            set
            {
                if (_id_etiqueta != value)
                {
                    Onid_etiquetaChanging(value);
                    ReportPropertyChanging("id_etiqueta");
                    _id_etiqueta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_etiqueta");
                    Onid_etiquetaChanged();
                }
            }
        }
        private global::System.Int32 _id_etiqueta;
        partial void Onid_etiquetaChanging(global::System.Int32 value);
        partial void Onid_etiquetaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String numero_etiqueta
        {
            get
            {
                return _numero_etiqueta;
            }
            set
            {
                Onnumero_etiquetaChanging(value);
                ReportPropertyChanging("numero_etiqueta");
                _numero_etiqueta = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("numero_etiqueta");
                Onnumero_etiquetaChanged();
            }
        }
        private global::System.String _numero_etiqueta;
        partial void Onnumero_etiquetaChanging(global::System.String value);
        partial void Onnumero_etiquetaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tipo_etiqueta
        {
            get
            {
                return _tipo_etiqueta;
            }
            set
            {
                Ontipo_etiquetaChanging(value);
                ReportPropertyChanging("tipo_etiqueta");
                _tipo_etiqueta = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tipo_etiqueta");
                Ontipo_etiquetaChanged();
            }
        }
        private global::System.String _tipo_etiqueta;
        partial void Ontipo_etiquetaChanging(global::System.String value);
        partial void Ontipo_etiquetaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String etiquetascol
        {
            get
            {
                return _etiquetascol;
            }
            set
            {
                OnetiquetascolChanging(value);
                ReportPropertyChanging("etiquetascol");
                _etiquetascol = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("etiquetascol");
                OnetiquetascolChanged();
            }
        }
        private global::System.String _etiquetascol;
        partial void OnetiquetascolChanging(global::System.String value);
        partial void OnetiquetascolChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_lote
        {
            get
            {
                return _id_lote;
            }
            set
            {
                Onid_loteChanging(value);
                ReportPropertyChanging("id_lote");
                _id_lote = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_lote");
                Onid_loteChanged();
            }
        }
        private global::System.Int32 _id_lote;
        partial void Onid_loteChanging(global::System.Int32 value);
        partial void Onid_loteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String clave_articulo
        {
            get
            {
                return _clave_articulo;
            }
            set
            {
                Onclave_articuloChanging(value);
                ReportPropertyChanging("clave_articulo");
                _clave_articulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("clave_articulo");
                Onclave_articuloChanged();
            }
        }
        private global::System.String _clave_articulo;
        partial void Onclave_articuloChanging(global::System.String value);
        partial void Onclave_articuloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_empaque
        {
            get
            {
                return _fecha_empaque;
            }
            set
            {
                Onfecha_empaqueChanging(value);
                ReportPropertyChanging("fecha_empaque");
                _fecha_empaque = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_empaque");
                Onfecha_empaqueChanged();
            }
        }
        private global::System.DateTime _fecha_empaque;
        partial void Onfecha_empaqueChanging(global::System.DateTime value);
        partial void Onfecha_empaqueChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_caducidad
        {
            get
            {
                return _fecha_caducidad;
            }
            set
            {
                Onfecha_caducidadChanging(value);
                ReportPropertyChanging("fecha_caducidad");
                _fecha_caducidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_caducidad");
                Onfecha_caducidadChanged();
            }
        }
        private global::System.DateTime _fecha_caducidad;
        partial void Onfecha_caducidadChanging(global::System.DateTime value);
        partial void Onfecha_caducidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_bodega
        {
            get
            {
                return _id_bodega;
            }
            set
            {
                Onid_bodegaChanging(value);
                ReportPropertyChanging("id_bodega");
                _id_bodega = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_bodega");
                Onid_bodegaChanged();
            }
        }
        private global::System.Int32 _id_bodega;
        partial void Onid_bodegaChanging(global::System.Int32 value);
        partial void Onid_bodegaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_usuario
        {
            get
            {
                return _id_usuario;
            }
            set
            {
                Onid_usuarioChanging(value);
                ReportPropertyChanging("id_usuario");
                _id_usuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_usuario");
                Onid_usuarioChanged();
            }
        }
        private global::System.Int32 _id_usuario;
        partial void Onid_usuarioChanging(global::System.Int32 value);
        partial void Onid_usuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single cantidad
        {
            get
            {
                return _cantidad;
            }
            set
            {
                OncantidadChanging(value);
                ReportPropertyChanging("cantidad");
                _cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cantidad");
                OncantidadChanged();
            }
        }
        private global::System.Single _cantidad;
        partial void OncantidadChanging(global::System.Single value);
        partial void OncantidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String unidad
        {
            get
            {
                return _unidad;
            }
            set
            {
                OnunidadChanging(value);
                ReportPropertyChanging("unidad");
                _unidad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("unidad");
                OnunidadChanged();
            }
        }
        private global::System.String _unidad;
        partial void OnunidadChanging(global::System.String value);
        partial void OnunidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> piezas
        {
            get
            {
                return _piezas;
            }
            set
            {
                OnpiezasChanging(value);
                ReportPropertyChanging("piezas");
                _piezas = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("piezas");
                OnpiezasChanged();
            }
        }
        private Nullable<global::System.Int32> _piezas;
        partial void OnpiezasChanging(Nullable<global::System.Int32> value);
        partial void OnpiezasChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SeguimientoContext", Name="lotes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class lotes : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto lotes.
        /// </summary>
        /// <param name="id_lote">Valor inicial de la propiedad id_lote.</param>
        /// <param name="id_usuario">Valor inicial de la propiedad id_usuario.</param>
        /// <param name="fecha_creacion">Valor inicial de la propiedad fecha_creacion.</param>
        public static lotes Createlotes(global::System.Int32 id_lote, global::System.Int32 id_usuario, global::System.DateTime fecha_creacion)
        {
            lotes lotes = new lotes();
            lotes.id_lote = id_lote;
            lotes.id_usuario = id_usuario;
            lotes.fecha_creacion = fecha_creacion;
            return lotes;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_lote
        {
            get
            {
                return _id_lote;
            }
            set
            {
                if (_id_lote != value)
                {
                    Onid_loteChanging(value);
                    ReportPropertyChanging("id_lote");
                    _id_lote = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_lote");
                    Onid_loteChanged();
                }
            }
        }
        private global::System.Int32 _id_lote;
        partial void Onid_loteChanging(global::System.Int32 value);
        partial void Onid_loteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_usuario
        {
            get
            {
                return _id_usuario;
            }
            set
            {
                Onid_usuarioChanging(value);
                ReportPropertyChanging("id_usuario");
                _id_usuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_usuario");
                Onid_usuarioChanged();
            }
        }
        private global::System.Int32 _id_usuario;
        partial void Onid_usuarioChanging(global::System.Int32 value);
        partial void Onid_usuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_creacion
        {
            get
            {
                return _fecha_creacion;
            }
            set
            {
                Onfecha_creacionChanging(value);
                ReportPropertyChanging("fecha_creacion");
                _fecha_creacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_creacion");
                Onfecha_creacionChanged();
            }
        }
        private global::System.DateTime _fecha_creacion;
        partial void Onfecha_creacionChanging(global::System.DateTime value);
        partial void Onfecha_creacionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SeguimientoContext", Name="pesos_fijos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class pesos_fijos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto pesos_fijos.
        /// </summary>
        /// <param name="clave_articulo">Valor inicial de la propiedad clave_articulo.</param>
        /// <param name="cantidad">Valor inicial de la propiedad cantidad.</param>
        public static pesos_fijos Createpesos_fijos(global::System.String clave_articulo, global::System.Single cantidad)
        {
            pesos_fijos pesos_fijos = new pesos_fijos();
            pesos_fijos.clave_articulo = clave_articulo;
            pesos_fijos.cantidad = cantidad;
            return pesos_fijos;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String clave_articulo
        {
            get
            {
                return _clave_articulo;
            }
            set
            {
                if (_clave_articulo != value)
                {
                    Onclave_articuloChanging(value);
                    ReportPropertyChanging("clave_articulo");
                    _clave_articulo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("clave_articulo");
                    Onclave_articuloChanged();
                }
            }
        }
        private global::System.String _clave_articulo;
        partial void Onclave_articuloChanging(global::System.String value);
        partial void Onclave_articuloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single cantidad
        {
            get
            {
                return _cantidad;
            }
            set
            {
                if (_cantidad != value)
                {
                    OncantidadChanging(value);
                    ReportPropertyChanging("cantidad");
                    _cantidad = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("cantidad");
                    OncantidadChanged();
                }
            }
        }
        private global::System.Single _cantidad;
        partial void OncantidadChanging(global::System.Single value);
        partial void OncantidadChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SeguimientoContext", Name="proveedores")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class proveedores : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto proveedores.
        /// </summary>
        /// <param name="id_proveedor">Valor inicial de la propiedad id_proveedor.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="estatus">Valor inicial de la propiedad estatus.</param>
        public static proveedores Createproveedores(global::System.Int32 id_proveedor, global::System.String nombre, global::System.Boolean estatus)
        {
            proveedores proveedores = new proveedores();
            proveedores.id_proveedor = id_proveedor;
            proveedores.nombre = nombre;
            proveedores.estatus = estatus;
            return proveedores;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_proveedor
        {
            get
            {
                return _id_proveedor;
            }
            set
            {
                if (_id_proveedor != value)
                {
                    Onid_proveedorChanging(value);
                    ReportPropertyChanging("id_proveedor");
                    _id_proveedor = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_proveedor");
                    Onid_proveedorChanged();
                }
            }
        }
        private global::System.Int32 _id_proveedor;
        partial void Onid_proveedorChanging(global::System.Int32 value);
        partial void Onid_proveedorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean estatus
        {
            get
            {
                return _estatus;
            }
            set
            {
                OnestatusChanging(value);
                ReportPropertyChanging("estatus");
                _estatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estatus");
                OnestatusChanged();
            }
        }
        private global::System.Boolean _estatus;
        partial void OnestatusChanging(global::System.Boolean value);
        partial void OnestatusChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SeguimientoContext", Name="unidades")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class unidades : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto unidades.
        /// </summary>
        /// <param name="id_unidad">Valor inicial de la propiedad id_unidad.</param>
        /// <param name="unidad">Valor inicial de la propiedad unidad.</param>
        public static unidades Createunidades(global::System.Int32 id_unidad, global::System.String unidad)
        {
            unidades unidades = new unidades();
            unidades.id_unidad = id_unidad;
            unidades.unidad = unidad;
            return unidades;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_unidad
        {
            get
            {
                return _id_unidad;
            }
            set
            {
                if (_id_unidad != value)
                {
                    Onid_unidadChanging(value);
                    ReportPropertyChanging("id_unidad");
                    _id_unidad = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_unidad");
                    Onid_unidadChanged();
                }
            }
        }
        private global::System.Int32 _id_unidad;
        partial void Onid_unidadChanging(global::System.Int32 value);
        partial void Onid_unidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String unidad
        {
            get
            {
                return _unidad;
            }
            set
            {
                OnunidadChanging(value);
                ReportPropertyChanging("unidad");
                _unidad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("unidad");
                OnunidadChanged();
            }
        }
        private global::System.String _unidad;
        partial void OnunidadChanging(global::System.String value);
        partial void OnunidadChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SeguimientoContext", Name="usuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class usuarios : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto usuarios.
        /// </summary>
        /// <param name="id_usuario">Valor inicial de la propiedad id_usuario.</param>
        /// <param name="username">Valor inicial de la propiedad username.</param>
        /// <param name="password">Valor inicial de la propiedad password.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="id_area">Valor inicial de la propiedad id_area.</param>
        public static usuarios Createusuarios(global::System.Int32 id_usuario, global::System.String username, global::System.String password, global::System.String nombre, global::System.Int32 id_area)
        {
            usuarios usuarios = new usuarios();
            usuarios.id_usuario = id_usuario;
            usuarios.username = username;
            usuarios.password = password;
            usuarios.nombre = nombre;
            usuarios.id_area = id_area;
            return usuarios;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_usuario
        {
            get
            {
                return _id_usuario;
            }
            set
            {
                if (_id_usuario != value)
                {
                    Onid_usuarioChanging(value);
                    ReportPropertyChanging("id_usuario");
                    _id_usuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_usuario");
                    Onid_usuarioChanged();
                }
            }
        }
        private global::System.Int32 _id_usuario;
        partial void Onid_usuarioChanging(global::System.Int32 value);
        partial void Onid_usuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_area
        {
            get
            {
                return _id_area;
            }
            set
            {
                Onid_areaChanging(value);
                ReportPropertyChanging("id_area");
                _id_area = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_area");
                Onid_areaChanged();
            }
        }
        private global::System.Int32 _id_area;
        partial void Onid_areaChanging(global::System.Int32 value);
        partial void Onid_areaChanged();

        #endregion
    
    }

    #endregion
    
}
