//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Seguimiento_y_Control.Entity.Internet
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class Portal_Entities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto Portal_Entities usando la cadena de conexión encontrada en la sección 'Portal_Entities' del archivo de configuración de la aplicación.
        /// </summary>
        public Portal_Entities() : base("name=Portal_Entities", "Portal_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto Portal_Entities.
        /// </summary>
        public Portal_Entities(string connectionString) : base(connectionString, "Portal_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto Portal_Entities.
        /// </summary>
        public Portal_Entities(EntityConnection connection) : base(connection, "Portal_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<empresas> empresas
        {
            get
            {
                if ((_empresas == null))
                {
                    _empresas = base.CreateObjectSet<empresas>("empresas");
                }
                return _empresas;
            }
        }
        private ObjectSet<empresas> _empresas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<usuarios> usuarios
        {
            get
            {
                if ((_usuarios == null))
                {
                    _usuarios = base.CreateObjectSet<usuarios>("usuarios");
                }
                return _usuarios;
            }
        }
        private ObjectSet<usuarios> _usuarios;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet empresas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToempresas(empresas empresas)
        {
            base.AddObject("empresas", empresas);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet usuarios. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTousuarios(usuarios usuarios)
        {
            base.AddObject("usuarios", usuarios);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Portal_Model", Name="empresas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class empresas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto empresas.
        /// </summary>
        /// <param name="id_empresa">Valor inicial de la propiedad id_empresa.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="nombre_corto">Valor inicial de la propiedad nombre_corto.</param>
        /// <param name="rfc">Valor inicial de la propiedad rfc.</param>
        /// <param name="calle">Valor inicial de la propiedad calle.</param>
        /// <param name="colonia">Valor inicial de la propiedad colonia.</param>
        /// <param name="ciudad">Valor inicial de la propiedad ciudad.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        /// <param name="direccion">Valor inicial de la propiedad direccion.</param>
        /// <param name="fecha">Valor inicial de la propiedad fecha.</param>
        /// <param name="ip">Valor inicial de la propiedad ip.</param>
        /// <param name="status">Valor inicial de la propiedad status.</param>
        /// <param name="cp">Valor inicial de la propiedad cp.</param>
        /// <param name="direccionlocal">Valor inicial de la propiedad direccionlocal.</param>
        public static empresas Createempresas(global::System.Int32 id_empresa, global::System.String nombre, global::System.String nombre_corto, global::System.String rfc, global::System.String calle, global::System.String colonia, global::System.String ciudad, global::System.String estado, global::System.String direccion, global::System.DateTime fecha, global::System.String ip, global::System.Int32 status, global::System.String cp, global::System.String direccionlocal)
        {
            empresas empresas = new empresas();
            empresas.id_empresa = id_empresa;
            empresas.nombre = nombre;
            empresas.nombre_corto = nombre_corto;
            empresas.rfc = rfc;
            empresas.calle = calle;
            empresas.colonia = colonia;
            empresas.ciudad = ciudad;
            empresas.estado = estado;
            empresas.direccion = direccion;
            empresas.fecha = fecha;
            empresas.ip = ip;
            empresas.status = status;
            empresas.cp = cp;
            empresas.direccionlocal = direccionlocal;
            return empresas;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_empresa
        {
            get
            {
                return _id_empresa;
            }
            set
            {
                if (_id_empresa != value)
                {
                    Onid_empresaChanging(value);
                    ReportPropertyChanging("id_empresa");
                    _id_empresa = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_empresa");
                    Onid_empresaChanged();
                }
            }
        }
        private global::System.Int32 _id_empresa;
        partial void Onid_empresaChanging(global::System.Int32 value);
        partial void Onid_empresaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre_corto
        {
            get
            {
                return _nombre_corto;
            }
            set
            {
                Onnombre_cortoChanging(value);
                ReportPropertyChanging("nombre_corto");
                _nombre_corto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre_corto");
                Onnombre_cortoChanged();
            }
        }
        private global::System.String _nombre_corto;
        partial void Onnombre_cortoChanging(global::System.String value);
        partial void Onnombre_cortoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String rfc
        {
            get
            {
                return _rfc;
            }
            set
            {
                OnrfcChanging(value);
                ReportPropertyChanging("rfc");
                _rfc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("rfc");
                OnrfcChanged();
            }
        }
        private global::System.String _rfc;
        partial void OnrfcChanging(global::System.String value);
        partial void OnrfcChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String calle
        {
            get
            {
                return _calle;
            }
            set
            {
                OncalleChanging(value);
                ReportPropertyChanging("calle");
                _calle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("calle");
                OncalleChanged();
            }
        }
        private global::System.String _calle;
        partial void OncalleChanging(global::System.String value);
        partial void OncalleChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String colonia
        {
            get
            {
                return _colonia;
            }
            set
            {
                OncoloniaChanging(value);
                ReportPropertyChanging("colonia");
                _colonia = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("colonia");
                OncoloniaChanged();
            }
        }
        private global::System.String _colonia;
        partial void OncoloniaChanging(global::System.String value);
        partial void OncoloniaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ciudad
        {
            get
            {
                return _ciudad;
            }
            set
            {
                OnciudadChanging(value);
                ReportPropertyChanging("ciudad");
                _ciudad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ciudad");
                OnciudadChanged();
            }
        }
        private global::System.String _ciudad;
        partial void OnciudadChanging(global::System.String value);
        partial void OnciudadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.String _estado;
        partial void OnestadoChanging(global::System.String value);
        partial void OnestadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String direccion
        {
            get
            {
                return _direccion;
            }
            set
            {
                OndireccionChanging(value);
                ReportPropertyChanging("direccion");
                _direccion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("direccion");
                OndireccionChanged();
            }
        }
        private global::System.String _direccion;
        partial void OndireccionChanging(global::System.String value);
        partial void OndireccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                OnfechaChanging(value);
                ReportPropertyChanging("fecha");
                _fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha");
                OnfechaChanged();
            }
        }
        private global::System.DateTime _fecha;
        partial void OnfechaChanging(global::System.DateTime value);
        partial void OnfechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ip
        {
            get
            {
                return _ip;
            }
            set
            {
                OnipChanging(value);
                ReportPropertyChanging("ip");
                _ip = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ip");
                OnipChanged();
            }
        }
        private global::System.String _ip;
        partial void OnipChanging(global::System.String value);
        partial void OnipChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.Int32 _status;
        partial void OnstatusChanging(global::System.Int32 value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cp
        {
            get
            {
                return _cp;
            }
            set
            {
                OncpChanging(value);
                ReportPropertyChanging("cp");
                _cp = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cp");
                OncpChanged();
            }
        }
        private global::System.String _cp;
        partial void OncpChanging(global::System.String value);
        partial void OncpChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String direccionlocal
        {
            get
            {
                return _direccionlocal;
            }
            set
            {
                OndireccionlocalChanging(value);
                ReportPropertyChanging("direccionlocal");
                _direccionlocal = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("direccionlocal");
                OndireccionlocalChanged();
            }
        }
        private global::System.String _direccionlocal;
        partial void OndireccionlocalChanging(global::System.String value);
        partial void OndireccionlocalChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Portal_Model", Name="usuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class usuarios : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto usuarios.
        /// </summary>
        /// <param name="idusuario">Valor inicial de la propiedad idusuario.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="usuario">Valor inicial de la propiedad usuario.</param>
        /// <param name="clave">Valor inicial de la propiedad clave.</param>
        /// <param name="correo">Valor inicial de la propiedad correo.</param>
        /// <param name="fecha">Valor inicial de la propiedad fecha.</param>
        /// <param name="acceso">Valor inicial de la propiedad acceso.</param>
        /// <param name="status">Valor inicial de la propiedad status.</param>
        /// <param name="id_empresa">Valor inicial de la propiedad id_empresa.</param>
        /// <param name="vendedor">Valor inicial de la propiedad vendedor.</param>
        /// <param name="puesto">Valor inicial de la propiedad puesto.</param>
        public static usuarios Createusuarios(global::System.Int32 idusuario, global::System.String nombre, global::System.String usuario, global::System.String clave, global::System.String correo, global::System.DateTime fecha, global::System.Int32 acceso, global::System.Int32 status, global::System.Int32 id_empresa, global::System.Int32 vendedor, global::System.String puesto)
        {
            usuarios usuarios = new usuarios();
            usuarios.idusuario = idusuario;
            usuarios.nombre = nombre;
            usuarios.usuario = usuario;
            usuarios.clave = clave;
            usuarios.correo = correo;
            usuarios.fecha = fecha;
            usuarios.acceso = acceso;
            usuarios.status = status;
            usuarios.id_empresa = id_empresa;
            usuarios.vendedor = vendedor;
            usuarios.puesto = puesto;
            return usuarios;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idusuario
        {
            get
            {
                return _idusuario;
            }
            set
            {
                if (_idusuario != value)
                {
                    OnidusuarioChanging(value);
                    ReportPropertyChanging("idusuario");
                    _idusuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idusuario");
                    OnidusuarioChanged();
                }
            }
        }
        private global::System.Int32 _idusuario;
        partial void OnidusuarioChanging(global::System.Int32 value);
        partial void OnidusuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String usuario
        {
            get
            {
                return _usuario;
            }
            set
            {
                OnusuarioChanging(value);
                ReportPropertyChanging("usuario");
                _usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("usuario");
                OnusuarioChanged();
            }
        }
        private global::System.String _usuario;
        partial void OnusuarioChanging(global::System.String value);
        partial void OnusuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String clave
        {
            get
            {
                return _clave;
            }
            set
            {
                OnclaveChanging(value);
                ReportPropertyChanging("clave");
                _clave = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("clave");
                OnclaveChanged();
            }
        }
        private global::System.String _clave;
        partial void OnclaveChanging(global::System.String value);
        partial void OnclaveChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String correo
        {
            get
            {
                return _correo;
            }
            set
            {
                OncorreoChanging(value);
                ReportPropertyChanging("correo");
                _correo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("correo");
                OncorreoChanged();
            }
        }
        private global::System.String _correo;
        partial void OncorreoChanging(global::System.String value);
        partial void OncorreoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                OnfechaChanging(value);
                ReportPropertyChanging("fecha");
                _fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha");
                OnfechaChanged();
            }
        }
        private global::System.DateTime _fecha;
        partial void OnfechaChanging(global::System.DateTime value);
        partial void OnfechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 acceso
        {
            get
            {
                return _acceso;
            }
            set
            {
                OnaccesoChanging(value);
                ReportPropertyChanging("acceso");
                _acceso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("acceso");
                OnaccesoChanged();
            }
        }
        private global::System.Int32 _acceso;
        partial void OnaccesoChanging(global::System.Int32 value);
        partial void OnaccesoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.Int32 _status;
        partial void OnstatusChanging(global::System.Int32 value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_empresa
        {
            get
            {
                return _id_empresa;
            }
            set
            {
                Onid_empresaChanging(value);
                ReportPropertyChanging("id_empresa");
                _id_empresa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_empresa");
                Onid_empresaChanged();
            }
        }
        private global::System.Int32 _id_empresa;
        partial void Onid_empresaChanging(global::System.Int32 value);
        partial void Onid_empresaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 vendedor
        {
            get
            {
                return _vendedor;
            }
            set
            {
                OnvendedorChanging(value);
                ReportPropertyChanging("vendedor");
                _vendedor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vendedor");
                OnvendedorChanged();
            }
        }
        private global::System.Int32 _vendedor;
        partial void OnvendedorChanging(global::System.Int32 value);
        partial void OnvendedorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String puesto
        {
            get
            {
                return _puesto;
            }
            set
            {
                OnpuestoChanging(value);
                ReportPropertyChanging("puesto");
                _puesto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("puesto");
                OnpuestoChanged();
            }
        }
        private global::System.String _puesto;
        partial void OnpuestoChanging(global::System.String value);
        partial void OnpuestoChanged();

        #endregion
    
    }

    #endregion
    
}
